server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/student_db
    username: mwas
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rest:
  template:
    connect-timeout: 10000
    read-timeout: 10000
